site_name: Scholastic Testing
pages:
    - Home: index.md
    - Methodology: methodology.md
    - Bugs: bugs.md
    - Checklists:
      - 'Reading Pro': 'checklists/reading_pro.md'
    - Plans:
      - User Acceptance Tests:
        - 'Reading Pro': 'plans/uat/reading_pro_uat_plan.md'
      - Performance Tests:
        - 'LBA': 'plans/perf/leveled_bookroom_accelerator_performance_test_plan.md'
        - 'NSGRA': 'plans/perf/nsgra_performance_test_plan.md'
        - 'Bookflix': 'plans/perf/bookflix_performance_test_plan.md'
      - Go Server Migration:
        - 'Load Balancer Re-platforming': 'plans/gsm/load_balancer_re-platformimg_plan.md'
    - Guides:
        - Installation:
          - 'Reading Pro': 'guides/reading_pro_installation_guide.md'
    - UML(s):
        - Environment Promotion: 'diagrams/environment_promotion.md'
    - Charles: 'tools/charles.md'
    - About: about.md
theme: material
